### ISSUE TITLE
An improper locking bug in the writerThread

### ISSUE THREAD

**Issue by ycaibb** [sobomax/bzip2smp#1]
Dear developers,
         Thank you for your checking. It seems there is an error(lock resource leak) due to the unreleased lock in the writerThread function. The resource lock outChunksMutex is not correctly released after the thread dummy has died.

https://github.com/sobomax/bzip2smp/blob/75a04a1b7c95469bea61fe3c3cb53f4ae6bec20f/bzip2smp.c#L175

 

The related code is shown below.

```
void * writerThread() { ...;

        pthread_mutex_lock( &outChunksMutex );

        for( ; ; ) { ...;

                  pthread_mutex_unlock( &outChunksMutex );

                  ...; 

                 pthread_mutex_lock( &outChunksMutex );

                 ...; } 

      // lack a unlock statement

}

int main( int argc, char *argv[] ) {

          if ( pthread_create( &dummy, NULL, &writerThread, NULL ) ) { note( 0, "Failed to create writer thread.\n" );

                      return 1;

}
```

Best,

**Comment by ycaibb** [comment]
Also, it seems the email ikm@users.sf.net can not be reached? @sobomax

`550 unknown user`

**Comment by sobomax** [comment]
Thanks, I'll look into it.

**Comment by sobomax** [comment]
@ycaibb I don't think your diagnosis is correct here. From the quick look to it, the writerThread() function never exits voluntarily unless fwrite() fails in which case it just causes the whole application to die. In the normal course the mutex is unlocked in the main thread before the program exits and at that point in time the writerThread() is most likely sleeping in the pthread_cond_wait(). Is there any way to cause program to misbehave?

**Comment by ycaibb** [comment]
@sobomax  Hi, thank you for your reply.
This is found by static code analysis, which warns of this case. It seems the lock can not be unlocked in the main thread?
https://github.com/sobomax/bzip2smp/blob/75a04a1b7c95469bea61fe3c3cb53f4ae6bec20f/bzip2smp.c#L558-L561

Also, why does `writerThread()` function never exits, which might be another error? From a quick look, my report could be wrong if the `writerThread()` function never exits. However when the program exits, the lock is still not released.

**Comment by sobomax** [comment]
@ycaibb I have no idea why your static analysis complains - perhaps too shallow and cannot see the whole picture? The chunk of the code that you posted is a textbook example of how you do a wait on a conditional variable. You enter pthread_cond_wait() in line 560 with the mutex being locked (line 558) and it **would unlock it for you while waiting** (allowing other threads to grab it and do a work) and then re-lock and return once condition has been signaled.

I suspect static analysis is missing the fact that a different pthread_cond_wait() in line 180 of the writerThread() would unlock the mutex and just wait forever in this situation allowing main() to proceed to completion:

`    if ( outChunksTail == -1 || ! outChunks[ outChunksTail ] )
      pthread_cond_wait( &outChunksFlushCondition, &outChunksMutex );`

Effectively, the writerThread() will most of the time be hanging in the pthread_cond_wait() with the outChunksMutex being **unlocked**, despite the code might be suggesting otherwise. Unless you consider how pthread_cond_wait() and overall program logic works.

The choice to never explicitly quit writerThread() is by original author of the software, it might not be the cleanest way but there is nothing wrong with that approach either since the whole process exits the OS will properly tear down any live threads once we exit main().

**Comment by ycaibb** [comment]
@sobomax Thank you very very much for your detailed reply. My question has been resolved.
